// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $counter from "./islands/counter.tsx";
import * as $date_picker from "./islands/date_picker.tsx";
import * as $gifcard from "./islands/gifcard.tsx";
import * as $ui_calendar_mod from "./islands/ui/calendar/mod.tsx";
import * as $ui_card_mod from "./islands/ui/card/mod.tsx";
import * as $ui_checkbox_mod from "./islands/ui/checkbox/mod.tsx";
import * as $ui_popover_mod from "./islands/ui/popover/mod.tsx";
import * as $ui_select_mod from "./islands/ui/select/mod.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/counter.tsx": $counter,
    "./islands/date_picker.tsx": $date_picker,
    "./islands/gifcard.tsx": $gifcard,
    "./islands/ui/calendar/mod.tsx": $ui_calendar_mod,
    "./islands/ui/card/mod.tsx": $ui_card_mod,
    "./islands/ui/checkbox/mod.tsx": $ui_checkbox_mod,
    "./islands/ui/popover/mod.tsx": $ui_popover_mod,
    "./islands/ui/select/mod.tsx": $ui_select_mod,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
